# Generated by Django 5.1.4 on 2026-01-19 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="storage_limit",
            field=models.BigIntegerField(default=10737418240),
        ),
    ]
