# Generated by Django 5.1.4 on 2026-01-01 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_userprofile_verification_token"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("FILE_UPLOAD", "File Uploaded"),
                            ("FILE_SHARE", "File Shared"),
                            ("FILE_DOWNLOAD", "File Downloaded"),
                            ("SHARE_ACCESSED", "Shared Link Accessed"),
                            ("FILE_DELETED", "File Deleted"),
                            ("FILE_RESTORED", "File Restored"),
                            ("STORAGE_WARNING", "Storage Warning"),
                            ("SYSTEM", "System Notification"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("file_name", models.CharField(blank=True, max_length=255, null=True)),
                ("file_id", models.IntegerField(blank=True, null=True)),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_read"],
                        name="accounts_no_user_id_a4ff2e_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="accounts_no_user_id_501ff2_idx",
                    ),
                ],
            },
        ),
    ]
