# Generated by Django 4.2.16 on 2025-10-28 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="sha256",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
