# Generated by Django 5.1.14 on 2025-11-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0002_alter_sharedlink_file_alter_sharedlink_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="sharedlink",
            name="is_email_only",
            field=models.BooleanField(default=False),
        ),
    ]
