# Generated by Django 4.2.16 on 2025-10-28 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0002_file_sha256"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="sha256",
            field=models.CharField(db_index=True, default="", max_length=64),
            preserve_default=False,
        ),
    ]
