# Generated by Django 5.1.4 on 2025-12-03 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0003_sharedlink_is_email_only"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
