# Generated by Django 4.2.16 on 2025-10-31 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("files", "0003_alter_file_sha256"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShareLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=12, unique=True)),
                ("token", models.CharField(max_length=64, unique=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("requires_password", models.BooleanField(default=False)),
                (
                    "password_hash",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("first_accessed_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("expiry_hours", models.IntegerField(default=24)),
                ("max_downloads", models.IntegerField(blank=True, null=True)),
                ("download_count", models.IntegerField(default=0)),
                ("view_count", models.IntegerField(default=0)),
                ("custom_message", models.TextField(blank=True)),
                ("notify_on_access", models.BooleanField(default=False)),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="share_links",
                        to="files.file",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "share_links",
            },
        ),
        migrations.CreateModel(
            name="ShareLinkAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accessed_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("view", "Viewed"),
                            ("download", "Downloaded"),
                            ("password_fail", "Wrong Password"),
                            ("expired", "Expired Link"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "share_link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accesses",
                        to="files.sharelink",
                    ),
                ),
            ],
            options={
                "db_table": "share_link_accesses",
                "indexes": [
                    models.Index(
                        fields=["share_link", "accessed_at"],
                        name="share_link__share_l_889d6d_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="sharelink",
            index=models.Index(fields=["slug"], name="share_links_slug_d18cab_idx"),
        ),
        migrations.AddIndex(
            model_name="sharelink",
            index=models.Index(
                fields=["expires_at", "is_active"],
                name="share_links_expires_9c58bd_idx",
            ),
        ),
    ]
