# Generated by Django 5.1.4 on 2025-12-03 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0004_file_deleted_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="file",
            options={"ordering": ["-uploaded_at"]},
        ),
        migrations.AlterModelOptions(
            name="filelog",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.AlterModelOptions(
            name="sharedlink",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="filelog",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="file",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="file",
            name="encryption_meta",
            field=models.TextField(blank=True, default="[]"),
        ),
        migrations.AlterField(
            model_name="file",
            name="sha256",
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="file",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="filelog",
            name="action",
            field=models.CharField(
                choices=[
                    ("UPLOAD", "Upload"),
                    ("DELETE", "Delete"),
                    ("RESTORE", "Restore"),
                    ("DOWNLOAD", "Download"),
                    ("SHARE", "Share"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="filelog",
            name="file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="files.file",
            ),
        ),
        migrations.AddIndex(
            model_name="file",
            index=models.Index(
                fields=["user", "deleted_at"], name="files_file_user_id_793d96_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="file",
            index=models.Index(fields=["sha256"], name="files_file_sha256_a19778_idx"),
        ),
    ]
