# Generated by Django 5.1.4 on 2026-01-11 05:02

import files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0005_alter_file_options_alter_filelog_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="cloudinary_public_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="file",
            name="cloudinary_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to=files.models.user_upload_path
            ),
        ),
    ]
