# Generated by Django 4.2.16 on 2025-11-04 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0005_sharedlink_remove_sharelinkaccess_share_link_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="encryption_meta",
            field=models.TextField(default="[]"),
        ),
        migrations.AlterField(
            model_name="file",
            name="sha256",
            field=models.CharField(max_length=64),
        ),
    ]
