# Generated by Django 5.1.4 on 2026-01-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0006_file_cloudinary_public_id_file_cloudinary_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="cloudinary_resource_type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
